## np.roll tutorial
a various examples of using roll to shift array elements </br>

<h3>Syntax:</h3>
numpy.roll(array, shift, axis = None)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# creating data
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# shift elements by 2, elements get circulated
np.roll(x, 2) 

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
# shift elements the opposite direction
np.roll(x, -2)

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

In [9]:
# creating two dimensional synthetic data
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
# shifting rows data by 2
np.roll(a, 2, axis=0)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [11]:
# shifting columns
np.roll(a, 2, axis=1)

array([[ 2,  3,  0,  1],
       [ 6,  7,  4,  5],
       [10, 11,  8,  9]])

In [12]:
# shifting both rows and columns
np.roll(a, (2,1))

array([[ 9, 10, 11,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])